service: lambda-forward-mail-imap

custom:
  stage: ${opt:stage, 'offline'}
  webpack:
    webpackConfig: './webpack.config.js'
    packager: 'npm'
    includeModules:
      forceExclude:
        - aws-sdk
        - aws-lambda
  serverless-offline:
    noPrependStageInUrl: true
  scheduleEnabled:
    prod: true
    offline: false

provider:
  name: aws
  region: 'eu-west-3'
  runtime: nodejs14.x
  logRetentionInDays: 1
  logs:
    httpApi: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ses:SendEmail
            - ses:SendRawEmail
          Resource: "*"

functions:
  forward_email:
    memorySize: 512
    timeout: 900
    handler: src/index.handler
    events:
      - schedule:
          rate: rate(5 minutes)
          enabled: ${self:custom.scheduleEnabled.${self:custom.stage}}

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-offline
